name: autotrie
description: A auto-completion engine for Dart/Flutter, based around an optimized Trie implementation.
version: 1.0.0+1
homepage: https://github.com/AKushWarrior/autotrie
repository: https://github.com/AKushWarrior/autotrie
issue_tracker: https://github.com/AKushWarrior/autotrie/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  hive_ce: ^2.11.3

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.26.2
